// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: key-value-store/kvstore.proto

package key_value_store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_key_value_store_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_value_store_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_key_value_store_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_key_value_store_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_value_store_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_key_value_store_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_key_value_store_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_value_store_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_key_value_store_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"` // 'optional' in proto3 means the field might not be set
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_key_value_store_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_value_store_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_key_value_store_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Optional: A wrapper message to encapsulate requests and responses
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*Command_Set
	//	*Command_Get
	Request isCommand_Request `protobuf_oneof:"request"`
	// Types that are valid to be assigned to Response:
	//
	//	*Command_SetResponse
	//	*Command_GetResponse
	Response      isCommand_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_key_value_store_kvstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_key_value_store_kvstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_key_value_store_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetRequest() isCommand_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Command) GetSet() *SetRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *Command) GetGet() *GetRequest {
	if x != nil {
		if x, ok := x.Request.(*Command_Get); ok {
			return x.Get
		}
	}
	return nil
}

func (x *Command) GetResponse() isCommand_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Command) GetSetResponse() *SetResponse {
	if x != nil {
		if x, ok := x.Response.(*Command_SetResponse); ok {
			return x.SetResponse
		}
	}
	return nil
}

func (x *Command) GetGetResponse() *GetResponse {
	if x != nil {
		if x, ok := x.Response.(*Command_GetResponse); ok {
			return x.GetResponse
		}
	}
	return nil
}

type isCommand_Request interface {
	isCommand_Request()
}

type Command_Set struct {
	Set *SetRequest `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type Command_Get struct {
	Get *GetRequest `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

func (*Command_Set) isCommand_Request() {}

func (*Command_Get) isCommand_Request() {}

type isCommand_Response interface {
	isCommand_Response()
}

type Command_SetResponse struct {
	SetResponse *SetResponse `protobuf:"bytes,3,opt,name=set_response,json=setResponse,proto3,oneof"`
}

type Command_GetResponse struct {
	GetResponse *GetResponse `protobuf:"bytes,4,opt,name=get_response,json=getResponse,proto3,oneof"`
}

func (*Command_SetResponse) isCommand_Response() {}

func (*Command_GetResponse) isCommand_Response() {}

var File_key_value_store_kvstore_proto protoreflect.FileDescriptor

const file_key_value_store_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x1dkey-value-store/kvstore.proto\x12\akvstore\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\vGetResponse\x12\x19\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05foundB\b\n" +
	"\x06_value\"\xe8\x01\n" +
	"\aCommand\x12'\n" +
	"\x03set\x18\x01 \x01(\v2\x13.kvstore.SetRequestH\x00R\x03set\x12'\n" +
	"\x03get\x18\x02 \x01(\v2\x13.kvstore.GetRequestH\x00R\x03get\x129\n" +
	"\fset_response\x18\x03 \x01(\v2\x14.kvstore.SetResponseH\x01R\vsetResponse\x129\n" +
	"\fget_response\x18\x04 \x01(\v2\x14.kvstore.GetResponseH\x01R\vgetResponseB\t\n" +
	"\arequestB\n" +
	"\n" +
	"\bresponseb\x06proto3"

var (
	file_key_value_store_kvstore_proto_rawDescOnce sync.Once
	file_key_value_store_kvstore_proto_rawDescData []byte
)

func file_key_value_store_kvstore_proto_rawDescGZIP() []byte {
	file_key_value_store_kvstore_proto_rawDescOnce.Do(func() {
		file_key_value_store_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_value_store_kvstore_proto_rawDesc), len(file_key_value_store_kvstore_proto_rawDesc)))
	})
	return file_key_value_store_kvstore_proto_rawDescData
}

var file_key_value_store_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_key_value_store_kvstore_proto_goTypes = []any{
	(*SetRequest)(nil),  // 0: kvstore.SetRequest
	(*GetRequest)(nil),  // 1: kvstore.GetRequest
	(*SetResponse)(nil), // 2: kvstore.SetResponse
	(*GetResponse)(nil), // 3: kvstore.GetResponse
	(*Command)(nil),     // 4: kvstore.Command
}
var file_key_value_store_kvstore_proto_depIdxs = []int32{
	0, // 0: kvstore.Command.set:type_name -> kvstore.SetRequest
	1, // 1: kvstore.Command.get:type_name -> kvstore.GetRequest
	2, // 2: kvstore.Command.set_response:type_name -> kvstore.SetResponse
	3, // 3: kvstore.Command.get_response:type_name -> kvstore.GetResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_key_value_store_kvstore_proto_init() }
func file_key_value_store_kvstore_proto_init() {
	if File_key_value_store_kvstore_proto != nil {
		return
	}
	file_key_value_store_kvstore_proto_msgTypes[3].OneofWrappers = []any{}
	file_key_value_store_kvstore_proto_msgTypes[4].OneofWrappers = []any{
		(*Command_Set)(nil),
		(*Command_Get)(nil),
		(*Command_SetResponse)(nil),
		(*Command_GetResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_value_store_kvstore_proto_rawDesc), len(file_key_value_store_kvstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_key_value_store_kvstore_proto_goTypes,
		DependencyIndexes: file_key_value_store_kvstore_proto_depIdxs,
		MessageInfos:      file_key_value_store_kvstore_proto_msgTypes,
	}.Build()
	File_key_value_store_kvstore_proto = out.File
	file_key_value_store_kvstore_proto_goTypes = nil
	file_key_value_store_kvstore_proto_depIdxs = nil
}
