// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: key-value-store/kvstore.proto

package key_value_store

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_key_value_store_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_value_store_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_key_value_store_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_key_value_store_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_value_store_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_key_value_store_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_key_value_store_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_value_store_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_key_value_store_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_key_value_store_kvstore_proto protoreflect.FileDescriptor

const file_key_value_store_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x1dkey-value-store/kvstore.proto\x12\x0fkey_value_store\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value2\x8d\x01\n" +
	"\rKeyValueStore\x12:\n" +
	"\x03Set\x12\x1b.key_value_store.SetRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x03Get\x12\x1b.key_value_store.GetRequest\x1a\x1c.key_value_store.GetResponseB8Z6github.com/atDoyle/distributed-systems/key-value-storeb\x06proto3"

var (
	file_key_value_store_kvstore_proto_rawDescOnce sync.Once
	file_key_value_store_kvstore_proto_rawDescData []byte
)

func file_key_value_store_kvstore_proto_rawDescGZIP() []byte {
	file_key_value_store_kvstore_proto_rawDescOnce.Do(func() {
		file_key_value_store_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_value_store_kvstore_proto_rawDesc), len(file_key_value_store_kvstore_proto_rawDesc)))
	})
	return file_key_value_store_kvstore_proto_rawDescData
}

var file_key_value_store_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_key_value_store_kvstore_proto_goTypes = []any{
	(*SetRequest)(nil),  // 0: key_value_store.SetRequest
	(*GetRequest)(nil),  // 1: key_value_store.GetRequest
	(*GetResponse)(nil), // 2: key_value_store.GetResponse
	(*empty.Empty)(nil), // 3: google.protobuf.Empty
}
var file_key_value_store_kvstore_proto_depIdxs = []int32{
	0, // 0: key_value_store.KeyValueStore.Set:input_type -> key_value_store.SetRequest
	1, // 1: key_value_store.KeyValueStore.Get:input_type -> key_value_store.GetRequest
	3, // 2: key_value_store.KeyValueStore.Set:output_type -> google.protobuf.Empty
	2, // 3: key_value_store.KeyValueStore.Get:output_type -> key_value_store.GetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_value_store_kvstore_proto_init() }
func file_key_value_store_kvstore_proto_init() {
	if File_key_value_store_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_value_store_kvstore_proto_rawDesc), len(file_key_value_store_kvstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_value_store_kvstore_proto_goTypes,
		DependencyIndexes: file_key_value_store_kvstore_proto_depIdxs,
		MessageInfos:      file_key_value_store_kvstore_proto_msgTypes,
	}.Build()
	File_key_value_store_kvstore_proto = out.File
	file_key_value_store_kvstore_proto_goTypes = nil
	file_key_value_store_kvstore_proto_depIdxs = nil
}
